name: Build RNTester

on:
  workflow_call:

jobs:
  build-rntester:
    name: "${{ matrix.platform }}, ${{ matrix.arch }}"
    runs-on: macos-26
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        platform: [macos, ios, visionos]
        arch: [oldarch, newarch]
        include:
          # Platform-specific properties
          - platform: macos
            sdk: macosx
            scheme: RNTester-macOS
            packager_platform: macos
          - platform: ios
            sdk: iphonesimulator
            scheme: RNTester
            packager_platform: ios
          - platform: visionos
            sdk: xrsimulator
            scheme: RNTester-visionOS
            packager_platform: ios
          # Architecture-specific properties
          - arch: oldarch
            new_arch_enabled: '0'
          - arch: newarch
            new_arch_enabled: '1'

    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0

      - name: Setup toolchain
        uses: ./.github/actions/microsoft-setup-toolchain
        with:
          node-version: '22'
          platform: ${{ matrix.platform }}
          project-root: 'packages/rn-tester'

      - name: Install npm dependencies
        run: yarn install

      - name: Install Pods
        working-directory: packages/rn-tester
        env:
          RCT_NEW_ARCH_ENABLED: ${{ matrix.new_arch_enabled }}
        run: |
          set -eox pipefail
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.base_ref }}" == "main" ]]; then
            yarn add @react-native-community/javascriptcore
            export USE_HERMES=0
            export USE_THIRD_PARTY_JSC=1
          fi
          bundle install
          bundle exec pod install --verbose

      - name: Build ${{ matrix.scheme }}
        env:
          USE_CCACHE: 0
        run: |
          set -eox pipefail
          .ado/scripts/xcodebuild.sh packages/rn-tester/RNTesterPods.xcworkspace ${{ matrix.sdk }} Debug ${{ matrix.scheme }} build
